version: "3.5"

services:
  api01: &api
    image: alanlopes/rinha-2024q1-dotnet
    hostname: api01
    depends_on:
      - capivara
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      TWIN_ADDRESS: api02
      LABEL: "api01"
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:3000
      ConnectionStrings__DB: Host=db:5432;Port=5432;Database=rinha;Username=admin;Password=123;Pooling=true;Minimum Pool Size=50;Maximum Pool Size=2000;Multiplexing=true;Timeout=15;Command Timeout=15;Cancellation Timeout=-1;No Reset On Close=true;Max Auto Prepare=20;Auto Prepare Min Usages=1;
      MAX_CONCURRENT_CONNECTIONS: 2000
      READ_POOL_SIZE: 1500
      WRITE_POOL_SIZE: 1000
      VIRTUAL_DB: capivara
      W_BASE_PORT: 50000
      R_BASE_PORT: 55000
      LISTENERS: 150
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"
  api02:
    <<: *api
    hostname: api02
    ports:
      - '3002:3000'
    environment:
      TWIN_ADDRESS: api01
      LABEL: "api02"
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:3000
      ConnectionStrings__DB: Host=db:5432;Port=5432;Database=rinha;Username=admin;Password=123;Pooling=true;Minimum Pool Size=50;Maximum Pool Size=2000;Multiplexing=true;Timeout=15;Command Timeout=15;Cancellation Timeout=-1;No Reset On Close=true;Max Auto Prepare=20;Auto Prepare Min Usages=1;
      MAX_CONCURRENT_CONNECTIONS: 2000
      READ_POOL_SIZE: 1500
      WRITE_POOL_SIZE: 1000
      VIRTUAL_DB: capivara
      R_BASE_PORT: 55150
      W_BASE_PORT: 50150
      LISTENERS: 150
  capivara:
    image: alanlopes/vdb-rinha-2024q1-dotnet
    hostname: capivara
    environment:
      W_BASE_PORT: 50000
      R_BASE_PORT: 55000
      LISTENERS: 300
    deploy:
      resources: 
        limits:
          cpus: "0.5"
          memory: "150MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "200MB"

networks: 
  default:
    driver: bridge
    name: rinha-nginx-2024q1